### ISSUE TITLE
Could you push your amp assets to maven central?

### ISSUE THREAD

**Issue by binduwavell** [javamelody/alfresco-javamelody#1]
Florian did a post on how to do this during beecon this year, I can find the link if you need me to?

**Comment by evernat** [comment]
Yes I can do it.
Which use case would need to have amp in maven central?

**Comment by binduwavell** [comment]
We use maven for dev projects with the Alfresco SDK, some of us build WAR files right out of these projects. Said WAR files can then be dropped into our deployment pipeline. 

Having pre packaged amps that are available from maven central makes this super easy. 

We have a yeoman generator that can create dev projects and a sub-generator that can add common useful amps from the community with a single CLI invocation, I'd love to add your project to generator-alfresco:amp-add-common.

I just ran across a more detailed article on pushing a project to maven central: https://dzone.com/articles/publish-your-artifacts-to-maven-central?utm_medium=feed&utm_source=feedpress.me&utm_campaign=Feed:+dzone/devops

**Comment by evernat** [comment]
done:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22alfresco-javamelody-addon%22

**Comment by binduwavell** [comment]
Awesome, thanks, I'll add this to the alfresco:amp-add-common yeoman generator (generator-alfresco).

**Comment by binduwavell** [comment]
This has been done an merged. If you are interested in trying this out:

``` sh
# install node (ideally a recent version)
npm install -g yo
npm install -g binduwavell/generator-alfresco
mkdir project
cd project
yo alfresco
# make sure to select SDK 2.2.0 (for Alfresco 5.1)
yo alfresco:amp-add-common
# select JavaMelody
./run-without-springloaded.sh
```

In a very short time (especially if you have node, you and generator-alfresco already installed.) You will have a brand new project with JavaMelody.

Thanks so much for the contribution to the Alfresco community, this is a fantastic tool for folks who want to understand the performance of their Alfresco installs!
